apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-oracle-database-connection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-oracle-database-connection
  template:
    metadata:
      labels:
        app: local-oracle-database-connection
    spec:
      containers:
        - name: local-oracle-database-connection
          image: sindriwest/argocd-app:v1.0
          ports:
            - containerPort: 8080