# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-database-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oracle-database-chart.name" . }}
    helm.sh/chart: {{ include "oracle-database-chart.chart" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.servicePort }}
      targetPort: {{ .Values.database.servicePort }}
  selector:
    app.kubernetes.io/name: {{ include "oracle-database-chart.name" . }}