# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: local-oracle-database-connection-service
spec:
  selector:
    app: local-oracle-database-connection
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080